name = "catalogo-templo-motor"
main = "src/index.js"
compatibility_date = "2025-12-28"

[assets]
directory = "./public"

[vars]
WOMPI_CURRENCY = "COP"

# IMPORTANTE: configura secretos en Cloudflare (no en Git)
# - WOMPI_INTEGRITY_SECRET
